DROP TABLE IF EXISTS color, person;

CREATE TABLE color (
color_id INT GENERATED BY DEFAULT AS IDENTITY
(START WITH 10 INCREMENT BY 10),
color_name VARCHAR NOT NULL
);


CREATE TABLE person (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(20) NOT NULL,
    surname VARCHAR(20) NOT NULL,
    identification_number UUID NOT NULL UNIQUE,
    age INT NOT NULL CHECK (age > 0),
    birth_date DATE,
    address VARCHAR(25),
    salary DECIMAL (18,2) DEFAULT 5000.00 CHECK (salary > 0)
);
